spring:
  datasource:
    url: jdbc:h2:mem:devdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # or create-drop if you want a fresh schema each run
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
